import { ActivatedRouteSnapshot } from '@angular/router';
import { RouterStateUrl } from '@app/root/store/reducers';

export const routerMocks: {
  description: string;
  snapshot: ActivatedRouteSnapshot;
  expect: RouterStateUrl;
}[] = [
  {
    description:
      'should return a correct RouterStateUrl object for `path1/subpath1/search`',
    snapshot: {
      component: null,
      data: {},
      fragment: null,
      outlet: 'primary',
      params: {},
      queryParams: { term: 'smells' },
      routeConfig: null,
      url: [],
      root: null,
      parent: null,
      children: null,
      pathFromRoot: null,
      paramMap: null,
      queryParamMap: null,
      firstChild: {
        component: null,
        data: {},
        fragment: null,
        outlet: 'primary',
        params: {},
        queryParams: { term: 'smells' },
        routeConfig: {
          loadChildren: '../section/section.module#SectionModule',
          path: 'path1',
        },
        url: [{ path: 'path1', parameters: {}, parameterMap: null }],
        root: null,
        parent: null,
        children: null,
        pathFromRoot: null,
        paramMap: null,
        queryParamMap: null,
        firstChild: {
          component: null,
          data: {},
          fragment: null,
          outlet: 'primary',
          params: {},
          queryParams: { term: 'smells' },
          routeConfig: {
            children: [],
            path: '',
          },
          url: [],
          root: null,
          parent: null,
          children: null,
          pathFromRoot: null,
          paramMap: null,
          queryParamMap: null,
          firstChild: {
            component: null,
            data: {
              section: 'subpath1',
            },
            fragment: null,
            outlet: 'primary',
            params: {},
            queryParams: { term: 'smells' },
            routeConfig: {
              loadChildren: '',
              path: '',
            },
            url: [{ path: 'subpath1', parameters: {}, parameterMap: null }],
            root: null,
            parent: null,
            children: null,
            pathFromRoot: null,
            paramMap: null,
            queryParamMap: null,
            firstChild: {
              component: null,
              data: {},
              fragment: null,
              outlet: 'primary',
              params: {},
              queryParams: { term: 'smells' },
              routeConfig: {
                loadChildren: '',
                path: '',
              },
              url: [{ path: 'search', parameters: {}, parameterMap: null }],
              root: null,
              parent: null,
              children: null,
              pathFromRoot: null,
              paramMap: null,
              queryParamMap: null,
              firstChild: {
                component: null,
                data: {
                  title: 'The title',
                },
                fragment: null,
                outlet: 'primary',
                params: {},
                queryParams: { term: 'smells' },
                routeConfig: {
                  loadChildren: '',
                  path: '',
                },
                url: [],
                root: null,
                parent: null,
                children: null,
                pathFromRoot: null,
                paramMap: null,
                queryParamMap: null,
                firstChild: null,
              },
            },
          },
        },
      },
    },
    expect: {
      params: {},
      paths: ['path1', 'subpath1', 'search'],
      title: 'The title',
      queryParams: {
        term: 'smells',
      },
      url: 'path1/subpath1/search',
      currentPage: 'subpath1',
    },
  },
  {
    description:
      'should return a correct RouterStateUrl object for `path1/subpath1/111`',
    snapshot: {
      component: null,
      data: {},
      fragment: null,
      outlet: 'primary',
      params: {},
      queryParams: {},
      routeConfig: null,
      url: [],
      root: null,
      parent: null,
      children: null,
      pathFromRoot: null,
      paramMap: null,
      queryParamMap: null,
      firstChild: {
        component: null,
        data: {},
        fragment: null,
        outlet: 'primary',
        params: {},
        queryParams: {},
        routeConfig: {},
        url: [{ path: 'path1', parameters: {}, parameterMap: null }],
        root: null,
        parent: null,
        children: null,
        pathFromRoot: null,
        paramMap: null,
        queryParamMap: null,
        firstChild: {
          component: null,
          data: {},
          fragment: null,
          outlet: 'primary',
          params: {},
          queryParams: {},
          routeConfig: {
            children: [],
            path: '',
          },
          url: [],
          root: null,
          parent: null,
          children: null,
          pathFromRoot: null,
          paramMap: null,
          queryParamMap: null,
          firstChild: {
            component: null,
            data: {
              section: 'subpath1',
            },
            fragment: null,
            outlet: 'primary',
            params: {},
            queryParams: {},
            routeConfig: {
              loadChildren: '',
              path: '',
            },
            url: [{ path: 'subpath1', parameters: {}, parameterMap: null }],
            root: null,
            parent: null,
            children: null,
            pathFromRoot: null,
            paramMap: null,
            queryParamMap: null,
            firstChild: {
              component: null,
              data: {},
              fragment: null,
              outlet: 'primary',
              params: { key: '111' },
              queryParams: {},
              routeConfig: {
                loadChildren: '',
                path: '',
              },
              url: [{ path: '111', parameters: {}, parameterMap: null }],
              root: null,
              parent: null,
              children: null,
              pathFromRoot: null,
              paramMap: null,
              queryParamMap: null,
              firstChild: {
                component: null,
                data: {
                  title: 'The title',
                },
                fragment: null,
                outlet: 'primary',
                params: {},
                queryParams: {},
                routeConfig: {
                  loadChildren: '',
                  path: '',
                },
                url: [],
                root: null,
                parent: null,
                children: null,
                pathFromRoot: null,
                paramMap: null,
                queryParamMap: null,
                firstChild: null,
              },
            },
          },
        },
      },
    },
    expect: {
      params: { key: '111' },
      paths: ['path1', 'subpath1', '111'],
      title: 'The title',
      queryParams: {},
      url: 'path1/subpath1/111',
      currentPage: 'subpath1',
    },
  },
];
